### ISSUE TITLE
Syntax for rule variables.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml-server#10]
How does the reified relationship predicate kind affect the variables in a predicate?

For example:

```
reified relationship Foo { ... }

Foo(source,x,y)
Foo(inverseSource,x,y)
```

What do the variables `x` and `y` bind to in each case?

The concern here is that adding support for specifying variables expands the expressiveness of rules that can be modeled in OML. For example, one could say `Foo(source,x,y)` and `Foo(source,y,x)`. This in turn leads to rules where the role of variables is not necessarily that of a simple chain. It is difficult to anticipate what the consequences of this additional expressiveness will be for the semantics of the language and for the computational complexity of reasoning with such expressive rules.

At this time, suggest removing support for explicit rule variables.

That is, the current OML rules are restricted to a subset of SWRL rules.
For details, see: https://omf.gitbooks.io/ontological-modeling-language-specification/content/GLOSSARY.html#oml-chainrule

**Comment by melaasar** [comment]
The explicitly added variables indeed allow for more expressiveness of the rule grammar, beyond a simple chain of variables, However, this is already supported by the SWRL language and reasoners like Pellet. With regard to readability, v0.5.0 introduced an intuitive textual syntax that will make it easier to read/write these rules. The syntax can be seen here:
https://github.com/opencaesar/oml-server/blob/master/oml-server/io.opencaesar.oml.dsl/src/main/java/io/opencaesar/oml/dsl/Oml.xtext
It will also soon be documented in the OML spec here:
https://opencaesar.github.io/oml-spec/
